### ISSUE TITLE
Pass env vars to JET packs

### ISSUE THREAD

**Issue by jcw** [jeelabs/jet#7]
As a way for the hub to provide some more info, context, settings, etc (from @tht).

**Comment by tht** [comment]
Looks like a good way to push down information about the MQTT connection down.The packs don't have to parse the command line, no escaping needed and the values are not visible to other processes/users on the same host.

Some stuff we should probably export:
* hub version
* path where the pack is registered in MQTT (`packs/abc`)
* mqtt url and credentials

And going further down that line there should be a way to configure custom environment variables when registering a new pack using the jet command. This allows for some generic packs, receiving all the configuration from environment variables.

**Comment by jcw** [comment]
Perfect suggestions. I'd be inclined to put the three things you mention in env vars, and leave more user-centric variations for cmd-line arguments.

**Comment by jcw** [comment]
```
2016/02/02 15:09:12 abc pack: export HUB_MQTT="tcp://localhost:1883"
2016/02/02 15:09:12 abc pack: export HUB_PACK="abc"
2016/02/02 15:09:12 abc pack: export HUB_VERSION="v4.0-26-gc88ce95 2016-02-02 (go1.5.3)"
```

**Comment by jcw** [comment]
Shelved, closing.
